= appBeforeIntegrationTest task
Andrey Hihlovskiy
2014-05-29
:sectanchors:
:jbake-type: page
:jbake-status: published

Gretty automatically invokes this task before integration test task, referred in
link:Gretty-configuration.html#_integrationtesttask[integrationTestTask] property of gretty configuration.

WARNING: Internal task, please, don't invoke it on command line!

== Effects

. Embedded servlet-container starts in separate java process against compiled classes and their dependencies and listens for HTTP-requests on link:Gretty-configuration.html#_port[port] (default 8080).
. Gradle script waits until servlet-container is online.
. Gradle script proceeds to integration test task.

== Instantiation and extension

The object called appBeforeIntegrationTest is actually an instance of link:Gretty-task-classes.html#_appbeforeintegrationtesttask[AppBeforeIntegrationTestTask] class, created and configured for you by Gretty. You can instantiate or even extend this class on your own:

[source,groovy]
----
apply plugin: 'org.akhikhl.gretty'

import org.akhikhl.gretty.AppBeforeIntegrationTestTask

task('MyBeforeIntegration', type: AppBeforeIntegrationTestTask) {
  // ...
}

class VerySpecialBeforeIntegration extends AppBeforeIntegrationTestTask {
  // ...
}

task('MyBeforeIntegration2', type: VerySpecialBeforeIntegration) {
  // ...
}
----

If you are going to instantiate or extend this task class yourself, make sure you've learned it's properties and methods.

See also: link:Integration-tests-support.html[integration tests support].
