= appStartWarDebug task
Andrey Hihlovskiy
2014-05-29
:sectanchors:
:jbake-type: page
:jbake-status: published

appStartWarDebug starts web-app on WAR-file, in debug mode.

== Syntax

[source,bash]
----
gradle appStartWarDebug
----

== Effects
. The web-app gets compiled and assembled into WAR-file (if it's not up-to-date).
. Embedded servlet-container starts in separate java process against WAR-file. +
*important*: Upon start, the process is in suspended-mode and listens for debugger commands on port 5005.
. Upon resume, servlet-container process starts listening for HTTP-requests on link:Gretty-configuration.html#_port[port] (default 8080).
. Gretty waits for servlet-container process to complete.
. Gradle script continues normal execution of tasks.

== Instantiation and extension

The object called appStartWarDebug is actually an instance of link:Gretty-task-classes.html#_appstarttask[AppStartTask] class, created and configured for you by Gretty. You can instantiate or even extend this class on your own:

[source,groovy]
----
apply plugin: 'org.akhikhl.gretty'

import org.akhikhl.gretty.AppStartTask

task('MyRun', type: AppStartTask) {
  // ...
}

class VerySpecialRun extends AppStartTask {
  // ...
}

task('MyRun2', type: VerySpecialRun) {
  // ...
}
----

If you are going to instantiate or extend this task class yourself, make sure you've learned it's properties and methods.

== Workflow

image::images/appStartWarDebug_StateDiagram.svg[]

See also: link:appStop-task.html[appStop task], link:appRestart-task.html[appRestart task], link:Debugger-support.html[Debugger support].

