= Farm integration tests
Andrey Hihlovskiy
2014-05-29
:sectanchors:
:jbake-type: page
:jbake-status: published

Gretty supports link:Integration-tests-support.html[integration tests] on link:Multiple-web-apps-introduction.html[farms], 
i.e. on multiple web-apps running on the same web-server.

You don't have to configure anything in order to use integration tests on farms. Your part is to create a farm and some integration tests, 
then run task:

[source,shell]
----
gradle farmIntegrationTest
----

Gretty automatically starts and stops a servlet container before and after integration tests.

Gretty automatically invokes all integration tests for all web-apps mentioned in a farm.

If you use named farms, then you have to invoked specific tasks for named farms. For example:

[source,groovy]
----
farms {
  farm 'XYZ', {
    webapp ':ProjectB'
    webapp ':ProjectC'
    webapp ':ProjectD'
  }
}
----

then you have to invoke:

[source,shell]
----
gradle farmIntegrationTestXYZ
----

There following example projects demonstrate farm integration tests at work:

https://github.com/akhikhl/gretty/tree/master/examples/farm[Simple farm]

https://github.com/akhikhl/gretty/tree/master/examples/farmSecure[Secure farm]

https://github.com/akhikhl/gretty/tree/master/examples/spring-boot-farm[Spring Boot farm]

https://github.com/akhikhl/gretty/tree/master/examples/spring-boot-farm-secure[Secure Spring Boot farm]

