= Getting started
Andrey Hihlovskiy
2014-05-29
:sectanchors:
:jbake-type: page
:jbake-status: published

Add the following to "build.gradle" of your web-app:

[source,groovy]
----
apply plugin: 'war'
apply from: 'https://raw.github.com/akhikhl/gretty/master/pluginScripts/gretty.plugin'
----

That's all! Now you can start your web-app with the command:

[source,bash]
----
gradle appRun
----

you can also use other link:Gretty-tasks[Gretty tasks] for running and debugging your web-app or link:Gretty-configuration.html[configure Gretty] to your needs.

Alternatively, you can download the script from https://raw.github.com/akhikhl/gretty/master/pluginScripts/gretty.plugin to the project folder and include it like this:

[source,groovy]
----
apply from: 'gretty.plugin'
----

or feel free inserting to your "build.gradle":

[source,groovy]
----
buildscript {
  repositories {
    jcenter()
    // enable this to use snapshot versions of Gretty:
    // maven { url 'http://oss.jfrog.org/artifactory/oss-snapshot-local' }
  }
  
  dependencies {
    classpath 'org.akhikhl.gretty:gretty:+'
  }
}

repositories {
  jcenter()
  // enable this to use snapshot versions of Gretty:
  // maven { url 'http://oss.jfrog.org/artifactory/oss-snapshot-local' }
}

apply plugin: 'org.akhikhl.gretty'
----

NOTE: All release versions of Gretty are available at jcenter and maven central under the group 'org.akhikhl.gretty'.

NOTE: Snapshot versions of gretty are available at jfrog artifactory (see code above).

IMPORTANT: If you experience problems starting Gretty, first look into link:Troubleshooting.html[troubleshooting] section. If it does not help, raise an issue at https://github.com/akhikhl/gretty/issues[Gretty issue tracker] or mailto:akhikhl@gmail.com[send an email] to Gretty developer.

