= Jetty security realms
Andrey Hihlovskiy
2014-05-29
:sectanchors:
:jbake-type: page
:jbake-status: published

Gretty configuration supports two properties related to Jetty security realms - +realm+ and +realmConfigFile+. When both properties are defined, Gretty applies the specified security realm to a web-app.

== Syntax

[source,groovy]
----
gretty {
  // ...
  servletContainer = 'jetty9'
  realm 'auth'
  realmConfigFile 'jetty-realm.properties'
  // ...
}
----

== Effects

+realm+ property defines security realm for the given web-app.
When specified, it must match /web-app/login-config/realm-name element
in "web.xml".

+realmConfigFile+ property defines relative (to webAppDir/WEB-INF folder)
path to the properties file, containing properties for HashLoginService.

+realm+ and +realmConfigFile+ affect only Gretty tasks. If you assemble WAR file and deploy it to some servlet container, you must define security realms by means of that
container.

Gretty contains example programs, demonstrating use of Jetty security realms:

* https://github.com/akhikhl/gretty/tree/master/examples/securityRealm7[securityRealm7]
* https://github.com/akhikhl/gretty/tree/master/examples/securityRealm8[securityRealm8]
* https://github.com/akhikhl/gretty/tree/master/examples/securityRealm9[securityRealm9]

See more information on Jetty security realms at: http://wiki.eclipse.org/Jetty/Tutorial/Realms.

