= jettyRunDebug task
Andrey Hihlovskiy
2014-05-29
:sectanchors:
:jbake-type: page
:jbake-status: published

jettyRunDebug starts web-app inplace, in debug and interactive mode.

== Syntax

[source,bash]
----
gradle jettyRunDebug
----

== Effects
.  The web-app gets compiled (if it's not up-to-date).
.  Embedded jetty starts in separate java process against compiled
classes and their dependencies. +
*important*: Upon start, the process is
in suspended-mode and listens for debugger commands on port 5005.
.  Upon resume, jetty process starts listening for HTTP-requests on
link:Gretty-configuration.html#port[port] (default 8080).
.  Gretty waits for the user keypress.
.  When user presses any key (in the same terminal), jetty process
shuts down.
.  Gretty waits for jetty process to complete.
.  Gradle script continues normal execution of tasks.

Note that this task does not depend on "war" task, nor does it use WAR-file.

== Instantiation and extension

The object called jettyRunDebug is actually an instance of link:Gretty-task-classes.html#jettystarttask[JettyStartTask] class, created and configured for you by Gretty. You can instantiate or even extend this class on your own:

[source,groovy]
----
apply plugin: 'gretty'

import org.akhikhl.gretty.JettyStartTask

task('MyRun', type: JettyStartTask) {
  // ...
}

class VerySpecialRun extends JettyStartTask {
  // ...
}

task('MyRun2', type: VerySpecialRun) {
  // ...
}
----

If you are going to instantiate or extend this task class yourself, make sure you've learned it's properties and methods.

== Workflow

image::http://akhikhl.github.io/gretty/media/jettyRunDebug_StateDiagram.svg[]

See also: link:Debugger-support.html[Debugger support].
