= Multiple web-apps configureless setup

Create three empty folders: ProjectA, ProjectB and ProjectC, so that folder tree looks like this:

----
ProjectA
|-- ProjectB
\-- ProjectC
----

Create file "ProjectA/settings.gradle", insert code: 

[source,groovy]
----
include 'ProjectA', 'ProjectB'
----

Explanation: we organize multi-project setup, so that multiple web-apps can be started/stopped by gretty-farm plugin.

Create file "ProjectA/build.gradle", insert code:

[source,groovy]
----
buildscript {
  repositories {
    jcenter()
  }

  dependencies {
    classpath 'org.akhikhl.gretty:gretty-plugin:+'
  }
}

apply plugin: 'gretty-farm'
----

Create file "ProjectA/ProjectB/build.gradle", insert code:

[source,groovy]
----
apply plugin: 'gretty'
----

Create file "ProjectA/ProjectC/build.gradle", insert code:

[source,groovy]
----
apply plugin: 'gretty'
----

Done! Now you can run multiple web-apps by running the following command in ProjectA:

[source,bash]
----
gradle farmRun
----

Expected output:

----
Jetty server 9.1.0.v20131115 started.
:ProjectB runs at the address http://localhost:8080/ProjectB
:ProjectC runs at the address http://localhost:8080/ProjectC
servicePort: 9900, statusPort: 9901
Press any key to stop the jetty server.
----

Of course, you'll get 404 in the browser, because web-apps don't contain any pages. But, as soon as you add pages or/and servlets to the web-apps, things will get real.

Now explanation on the details of what we just did. We defined three gradle projects: two facilitated with gretty plugin and one - with gretty-farm plugin. +
The projects with gretty plugin are usual web-apps, potentially with src/main/webapp, configuration files, servlets etc.etc. +
The project with gretty-farm plugin is special. It defines *farm* - logical group of web-apps that should run together. 

By default farm automatically adds all subprojects of the farm project, which are facilitated with gretty plugin, to web-apps list. On the link:Configuring-default-farm[next page] you'll see how you can control, which projects are added to a farm.

Gretty-farm plugin also defines new, distinct set of tasks for running farms: farmRun, farmRunDebug, farmRunWar, farmRunWarDebug, etc. (see complete list of farm tasks link:Farm-tasks[here]).

See also: link:index#Multiple-web-apps[Multiple web-apps].
