= Spring Boot support
Andrey Hihlovskiy
2014-05-29
:sectanchors:
:jbake-type: page
:jbake-status: published

Since version 0.0.24 Gretty supports Spring Boot web-apps out-of-the-box.
All Gretty features, including (but not limited to) debugging,
code coverage and integration tests, also apply to spring-boot web-apps. 
See more information below.

== Simplest Gretty setup with Spring Boot 

Add the following code to "build.gradle":

[source,groovy]
----
buildscript {
  repositories {
    mavenLocal()
    jcenter()
  }

  dependencies {
    classpath 'org.akhikhl.gretty:gretty:+'
  }
}

apply plugin: 'gretty'

gretty {
  springBoot = true
}
----

Now you can run your Spring Boot application with the command `gradle appRun`.

The complete sources for the simplest Gretty Spring Boot setup:

* https://github.com/akhikhl/gretty/tree/master/examples/spring-boot-simple[spring-boot-simple]

== Running on specific version of spring boot

Add the following code to "build.gradle":

[source,groovy]
----
buildscript {
  repositories {
    mavenLocal()
    jcenter()
    maven { url 'http://repo.spring.io/release' }
  }

  dependencies {
    classpath 'org.akhikhl.gretty:gretty:+'
  }
}

apply plugin: 'gretty'

gretty {
  springBootVersion = '1.1.7.RELEASE'
}
----

Note that spring-boot versions prior to 1.1.0 are not supported by Gretty and may produce compile-time or runtime errors.

== Gretty configuration and Spring Boot

Gretty configuration also applies to spring-boot projects. You can set properties like "contextPath", "port", etc. etc. - they all
will be passed to the servlet container and web-app.

== Gretty tasks and Spring Boot

Gretty plugin implements all gretty tasks for spring-boot projects.

== Gretty hot-deployment and Spring Boot

Gretty uses https://github.com/spring-projects/spring-loaded[spring-loaded] library for smooth reload
of running Spring Boot applications. As soon as you change the sources, the project gets 
automatically recompiled and web-app reloads with updated classes.

Gretty also supports link:Fast-reload.html[Fast reload] feature with Spring Boot web-apps.

== Gretty webapp-overlays and Spring Boot

Webapp-overlays are technically possible with Gretty and Spring Boot, but author of Gretty plugin
did not test this feature yet. See more information in link:Web-app-overlays.html[Web-app overlays] section.

== Gretty HTTPS support and Spring Boot

Gretty fully supports link:HTTPS-support.html[HTTPS] with Spring Boot web-apps.

== Gretty debugging, testing, logging and Spring Boot

Gretty fully supports link:Debugger-support.html[debugging] of Spring Boot web-apps.

Gretty fully supports link:Integration-tests-support.html[integration tests] with Spring Boot web-apps.

Gretty fully supports link:Code-coverage-support.html[Jacoco code coverage] with Spring Boot web-apps.

Gretty fully supports link:Logging.html[logging] of Spring Boot web-apps.

== Gretty Jetty-specific features and Spring Boot

Gretty fully supports link:Jetty-security-realms.html[Jetty security realms] with Spring Boot web-apps.

Gretty fully supports link:jetty.xml-support.html[jetty.xml] with Spring Boot web-apps.

Gretty fully supports link:jetty-env.xml-support.html[jetty-env.xml] with Spring Boot web-apps.

== Gretty Tomcat-specific features and Spring Boot

Gretty fully supports link:Tomcat-security-realms.html[Tomcat security realms] with Spring Boot web-apps.

== Gretty multiple web-apps and Spring Boot

Gretty supports running multiple web-apps on so-called link:Multiple-web-apps-introduction.html[farms].
Web-apps can be Spring Boot or "normal", in any combinations - Gretty will sort them out.

Gretty contains example program, showing multi-web-app setup with Spring Boot:

* https://github.com/akhikhl/gretty/tree/master/examples/spring-boot-farm[spring-boot-farm]

== Servlet container versions and Spring Boot

Gretty supports running Spring Boot web-apps on Jetty 8/9 and Tomcat 7/8. Running Spring Boot on Jetty 7 is not supported, since Jetty 7 uses older servlet API not compatible with Spring Boot.

The servlet container for Spring Boot web-apps is selected via link:Gretty-configuration.html#_servletcontainer[servletContainer] property of Gretty configuration.

