= Switching between jetty and servlet-API versions
Andrey Hihlovskiy
2014-05-29
:sectanchors:
:jbake-type: page
:jbake-status: published

Starting with version 1.0.0, Gretty supports unified interface to the servlet containers
Jetty 7, 8 and 9, Tomcat 7 and 8. There's only one plugin to include: `org.akhikhl.gretty`.

The syntax:

[source,groovy]
----
apply from: 'https://raw.github.com/akhikhl/gretty/master/pluginScripts/gretty.plugin'
apply from: 'war' // optional, if you use spring-boot


----


To use specific version of jetty and servlet API, add one of the
following to "build.gradle" of your web-app (instead of
"gretty.plugin"):

[source,groovy]
----
apply from: 'https://raw.github.com/akhikhl/gretty/master/pluginScripts/gretty7.plugin'
----

This adds jetty 7.6.14.v20131031 and servlet API 2.5 to the web-app.

[source,groovy]
----
apply from: 'https://raw.github.com/akhikhl/gretty/master/pluginScripts/gretty8.plugin'
----

This adds jetty 8.1.8.v20121106 and servlet API 3.0.1 to the web-app.

[source,groovy]
----
apply from: 'https://raw.github.com/akhikhl/gretty/master/pluginScripts/gretty9.plugin'
----

This adds jetty 9.1.0.v20131115 and servlet API 3.1.0 to the web-app.

WARNING: please _do not_ add several variants of grettyX.plugin at
the same time. Only one of the abovementioned plugins should be used 
in the same web-app.

Of course, you can download any of these scripts from github to the
project folder and include it like this:

[source,groovy]
----
apply from: 'gretty7.plugin'
----

or feel free copying (and modifying) the declarations from these scripts
to your "build.gradle".
