= Web-app filtering
Andrey Hihlovskiy
2014-05-29
:sectanchors:
:jbake-type: page
:jbake-status: published

Since version 1.1.2-SNAPSHOT Gretty can filter files in "src/main/webapp" the same way as processResources can filter files in "src/main/resources".

IMPORTANT: Web-app filtering feature is in incubation phase and currently is only available in Gretty 1.1.2-SNAPSHOT. See https://github.com/akhikhl/gretty#star-whats-new[Gretty What's New] section to learn how to configure Gradle script for using snapshot versions of Gretty.

== Syntax

[source,groovy]
----
gretty {
  webappCopy { CopySpec copySpec ->
     // ...
  }
}
----

here webappCopy is a closure, accepting org.gradle.api.file.CopySpec as a parameter.

== Effects

webappCopy closure is automatically invoked when:

- gradle performs one of Gretty run tasks
- gradle builds WAR file
- gradle builds a link:Product-generation.html[product]

TIP: There's no need to duplicate CopySpec-specific code in gretty and War task. You can hold all filtering code in gretty.webappCopy. Gretty automatically reconfigures War task with gretty.webappCopy.

Gretty sources contain https://github.com/akhikhl/gretty/tree/master/examples/filterWebapp[example program] demonstrating web-app filtering at work.

